shapevibe/gift/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'gift'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.login_user, name='login_user'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate, name='activate'),
    url(r'^profile/(?P<username>[\w|\W.-]+)/$', views.view_profile, name='view_profile'),
    url(r'^profile/edit$', views.update_profile, name='update_profile'),
    url(r'^delete_user/(?P<username>[\w|\W.-]+)/$', views.delete_user, name='delete_user'),
    url(r'^(?P<gift_id>[0-9]+)/modal/$', views.modal, name='modal'),
    url(r'^(?P<gift_id>[0-9]+)/detail/$', views.detail, name='detail'),
    url(r'^(?P<gift_id>[0-9]+)/edit/$', views.edit_gift, name='edit_gift'),
    url(r'^(?P<gift_id>[0-9]+)/delete/$', views.delete_gift, name='delete_gift'),
    url(r'^create_gift/$', views.create_gift, name='create_gift'),
]

shapevibe/shapevibe/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from gift import views
from django.contrib.auth import views as auth_views


admin.site.site_header = settings.ADMIN_SITE_HEADER


urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'alpha/', include('gift.urls')),
    url(r'^', include('gift.urls')),
    url(r'alpha/about/$', views.about, name='about'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url('^', include('django.contrib.auth.urls')),
    url(r'^password_reset/$', auth_views.password_reset),
    url(r'^password_reset/done/$', auth_views.password_reset_done),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', auth_views.password_reset_confirm),
    url(r'^reset/done/$', auth_views.password_reset_complete),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shapevibe/gift/models.py
from django.db import models
from django.contrib.postgres.fields import ArrayField
from django.contrib.auth.models import User, AbstractUser
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.conf import settings
from .validators import validate_img_file_extension, validate_audio_file_extension
import datetime

# Create your models here.
class Gift(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, default=1, on_delete=models.CASCADE)
    gift_title = models.CharField(max_length=250)
    gift_description = models.TextField(max_length=2000)
    gift_image = models.FileField(blank=True, validators=[validate_img_file_extension])
    gift_audio = models.FileField(upload_to='audio_files/', blank=True, validators=[validate_audio_file_extension])
    price = models.PositiveIntegerField(blank=True, null=True)
    created_at = models.DateField(auto_now_add=True)
    tags = ArrayField(models.CharField(max_length=50), blank=True, null=True, default=[])
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.gift_title + ' - ' + self.user.username

    def split_tags(self):
        return self.tags.split(',')

    def handle_tags_when_free(self):
        if self.price is None or 0:
            self.tags.append('free')
        else:
            if 'free' in self.tags:
                self.tags.remove('free')
        return self.tags

    # def save(self, force_insert=False, force_update=False):
    #     super(Gift, self).save(force_insert, force_update)
    #
    #     if self.id is not None:
    #         previous = Gift.objects.get(id=self.id)
    #         if self.gift_image and self.gift_image != previous.gift_image:
    #             image = Image.open(self.gift_image.path)
    #             image = image.resize((96, 96), Image.ANTIALIAS)
    #             image.save(self.gift_image.path)

# class Tag(models.Model):
#     name = models.CharField(max_length=25, on_delete=models.CASCADE, blank=True, null=True)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=15, blank=True)
    last_name = models.CharField(max_length=20, blank=True)
    summary = models.TextField(max_length=500, blank=True)
    avatar = models.FileField(upload_to='avatars/', blank=True, validators=[validate_img_file_extension])
    tags = ArrayField(models.CharField(max_length=50), blank=True, null=True, default=[])
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.user.username + ': ' + self.first_name + ' ' + self.last_name

    @receiver(post_save, sender=User)
    def create_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)

    @receiver(post_save, sender=User)
    def save_user_profile(sender, instance, **kwargs):
        instance.profile.save()

    # def save(self, force_insert=False, force_update=False):
    #     super(Profile, self).save(force_insert, force_update)
    #
    #     if self.id is not None:
    #         previous = Profile.objects.get(id=self.id)
    #         if self.avatar and self.avatar != previous.avatar:
    #             image = Image.open(self.avatar.path)
    #             image = image.resize((96, 96), Image.ANTIALIAS)
    #             image.save(self.avatar.path)

shapevibe/gift/forms.py
from django import forms
from django.forms import fields
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from .models import Gift, Profile

AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg', '.tif', '.tiff']

class GiftForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(GiftForm, self).__init__(*args, **kwargs)
        self.fields['gift_image'].label = 'Image: File must be PNG, JPG, JPEG, TIF, or TIFF'
        self.fields['gift_audio'].label = 'Audio: File must be WAV, MP3, or OGG'
        self.fields['price'].label = 'Price: Leave blank if gift is free.'
        self.fields['tags'].label = 'Tags: *Separate each value with comma. 5 max.'

    class Meta:
        model = Gift
        fields = ['gift_title', 'gift_description', 'gift_image', 'gift_audio', 'price', 'tags']


class UserForm(forms.ModelForm):
    email = forms.CharField(required=True, max_length=32)
    #password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email')

class ProfileForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(ProfileForm, self).__init__(*args, **kwargs)
        self.fields['avatar'].label = 'Image: File must be PNG, JPG, JPEG, TIF, or TIFF'
        self.fields['tags'].label = 'Tags: *Separate each value with comma. 5 max.'

    class Meta:
        model = Profile
        fields = ('first_name', 'last_name', 'summary', 'avatar', 'tags')

class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control'
        self.fields['email'].widget.attrs['class'] = 'form-control'
        self.fields['password1'].widget.attrs['class'] = 'form-control'
        self.fields['password2'].widget.attrs['class'] = 'form-control'

    email = forms.EmailField(max_length=200, help_text='Required')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        widgets = {
            'email': forms.TextInput(attrs={'class': 'form-control'}),
        }

shapevibe/gift/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import logout
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.db.models import Q
from .tokens import account_activation_token
from .forms import GiftForm, UserForm, SignupForm, ProfileForm
from .models import Gift
import datetime

# AUDIO_FILE_TYPES = ['wav', 'mp3', 'ogg']
# IMAGE_FILE_TYPES = ['png', 'jpg', 'jpeg', '.tif', '.tiff']


# Create your views here.
def about(request):
    return render(request, 'gift/about.html')


@login_required
def index(request):
    user = request.user
    gifts = Gift.objects.all().order_by('-updated_at') # limit up to 50?
    users = User.objects.all()
    query = request.GET.get("q")
    if query:
        # soon will filter by tags as well
        gifts = Gift.objects.filter(
            Q(gift_title__icontains=query) |
            Q(gift_description__icontains=query) |
            Q(tags__icontains=query)
        ).distinct().order_by('-id')
        users = users.filter(
            Q(username__contains=query) |
            Q(profile__first_name__iexact=query) |
            Q(profile__last_name__iexact=query) |
            Q(profile__first_name__icontains=query, profile__last_name__icontains=query) |
            Q(profile__tags__iexact=query)
        ).distinct()
        return render(request, 'gift/index.html', {'gifts': gifts, 'users': users, 'query': query})
    else:
        return render(request, 'gift/index.html', {'user': user, 'gifts': gifts})

@login_required
def detail(request, gift_id):
    user = request.user
    gift = get_object_or_404(Gift, pk=gift_id)
    gifts_posted_by_user = Gift.objects.filter(user=user).order_by('-created_at')
    return render(request, 'gift/detail.html', {'gift': gift, 'user': user, 'gifts': gifts_posted_by_user})

@login_required
def modal(request, gift_id):
    # user = request.user
    gift = get_object_or_404(Gift, pk=gift_id)
    return render(request, 'gift/modal.html', {'gift': gift})

# CREATE, UPDATE, DELETE GIFT
@login_required
def create_gift(request):
    if request.method == 'POST':
        form = GiftForm(request.POST, request.FILES)
        if form.is_valid():
            gift = form.save(commit=False)
            gift.user = request.user
            if gift.gift_audio:
                audio_file_type = gift.gift_audio.url.split('.')[-1].lower()
                gift.handle_tags_when_free()
                gift.save()
                return render(request, 'gift/detail.html', {'gift': gift, 'audio_file_type': audio_file_type})
            else:
                gift.handle_tags_when_free()
                gift.save()
            return render(request, 'gift/detail.html', {'gift': gift})
        else:
            # FIND OUT HOW TO SHOW Validation ERROR MESSAGE
            error_message = 'Unsupported file.'
            form = GiftForm()
            return render(request, 'gift/create_gift.html', {'form': form, 'error_message': error_message})
    else:
        form = GiftForm()
    return render(request, 'gift/create_gift.html', {'form': form})

@login_required
def edit_gift(request, gift_id):
    gift = get_object_or_404(Gift, pk=gift_id)
    viber = gift.user
    if request.user != viber:
        return redirect('gift:detail', gift_id=gift_id)
    if request.method == 'POST':
        form = GiftForm(request.POST, request.FILES, instance=gift)
        try:
            if form.is_valid():
                gift = form.save(commit=False)
                if gift.gift_audio:
                    audio_file_type = gift.gift_audio.url.split('.')[-1].lower()
                gift.handle_tags_when_free()
                gift.save()
                return render(request, 'gift/detail.html', {'gift': gift, 'success_message':'Successfully edited gift.'})
        except:
            context = {
                'gift': gift,
                'form': form,
                'error_message': 'Unsupported file.',
            }
            return render(request, 'gift/edit_gift.html', context)
    else:
        form = GiftForm(instance=gift)
        return render(request, 'gift/edit_gift.html', {'form':form, 'gift': gift})

@login_required
def delete_gift(request, gift_id):
    gift = Gift.objects.get(pk=gift_id)
    gift.delete()
    return redirect('gift:view_profile', username=request.user.username)

# Profile views
@login_required
def view_profile(request, username):
    user = request.user
    profile = User.objects.get(username=username)
    gifts_posted_by_user = Gift.objects.filter(user=user).order_by('-created_at')
    gifts_by_viewed_user = Gift.objects.filter(user=profile).order_by('-created_at')
    preview_most_recent_gifts = Gift.objects.filter(user=user).order_by('-updated_at')[:2]
    return render(request, 'gift/profile.html', {
                                                    'user': user,
                                                    'profile': profile,
                                                    'gifts': gifts_posted_by_user,
                                                    'profile_gifts': gifts_by_viewed_user,
                                                    'gifts_by_viewed_user': gifts_by_viewed_user,
                                                    'recent_gifts': preview_most_recent_gifts,

                                                })

@login_required
def update_profile(request):
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile = profile_form.save(commit=False)
            profile.save()
            context = {
                'user': request.user,
                'profile': request.user,
                'gifts': Gift.objects.filter(user=request.user).order_by('-created_at'),
                'recent_gifts': Gift.objects.filter(user=request.user).order_by('-created_at')[:2],
                'success_message': 'You succesfully updated your profile',
            }
            return render(request, 'gift/profile.html', context)
        else:
            context = {
                'user_form': user_form,
                'profile_form': profile_form,
                'error_message': 'Error saving profile info',
            }
            return render(request, 'gift/edit_profile.html', context)
    else:
        user = request.user
        user_form = UserForm(instance=user)
        profile_form = ProfileForm(instance=user.profile)
    return render(request, 'gift/edit_profile.html', {'user': user, 'user_form': user_form, 'profile_form': profile_form})

@login_required
def delete_user(request, username):
    try:
        user = User.objects.get(username=username)
        user.delete()
        return render(request, 'gift/delete.html', {'success_message': 'You Successfully deleted your account.'})
    except:
        error_message = 'Something went wrong.'
    return render(request, 'gift/delete.html', {'error_message': error_message})

# Authentication
def logout_user(request):
    logout(request)
    return redirect('gift:login_user')

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                gifts = Gift.objects.all().order_by('-updated_at') # or filter by user
                return render(request, 'gift/index.html', {'gifts': gifts, 'user':user})
            else:
                return render(request, 'gift/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'gift/login.html', {'error_message': 'Invalid login'})
    return render(request, 'gift/login.html')

def register(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            username = request.POST['username']
            existing = User.objects.filter(username__iexact=username)
            if existing.exists():
                return render(request, 'gift/register.html', {'form': SignupForm(), 'error_message': 'Username already taken.',})
            user.save()
            current_site = get_current_site(request)
            mail_subject = 'Activate your blog account'
            message = render_to_string('gift/acc_active_email.html', {
                'user': user,
                'domain': current_site,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)).decode(),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(mail_subject, message, to=[to_email])
            email.send()
            # probably a good idea to make a template
            return render(request, 'gift/registration_next.html')
    else:
        form = SignupForm()
    return render(request, 'gift/register.html', {'form': form})

def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)

shapevibe/gift/templates/gift/acc_active_email.html
{% autoescape off %}

Welcome to Shapevibe!,
Please click on the link to confirm your registration,
http://{{ domain }}{% url 'gift:activate' uidb64=uid token=token %}

{% endautoescape %}

shapevibe/gift/templates/gift/detail.html
{% extends 'gift/base.html' %}
{% block title %}{{gift}}{% endblock %}
{% load static %}

{% block body %}
<div class="container" style="width:100%;">
    <!-- shapevibe logo and home/profile logo -->
        <a href="{% url 'gift:index' %}" style="margin-left:0.5em;margin-top:2em;display:block;"><img src="{% static 'gift/img/iconMedium.png' %}" width="80px" class="img-responsive" alt=""></a><br>
        <a href="{% url 'gift:logout_user' %}" style="color:white;margin-left:0.5em;">Logout</a>
    <div class="row">
        <div class="col-xs-10 col-xs-offset-1 col-sm-10 col-sm-offset-1 col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2 profile-wrapper" style="margin-top:-5em;">
            <div class="top-bar" style="width:100%; display:flex; justify-content: space-around; height:6em;">
                <img id="giftIcon" src="{% static 'gift/img/gift.png' %}"  class="img-responsive" style="margin-bottom:0.25em;margin-left:4em;display:block;" alt="">
                <a href="{% url 'gift:create_gift' %}"><button id="giftButton" class="btn btn-primary" style="display:none;height:2em;margin-top:2em;">Add Gift +</button></a>
            </div>
            <div class="panel panel-default" style="height:450px;overflow-y:scroll">
                <div class="row">
                    <div class="gift-list" id="giftList" style="
                            height: auto;
                            width:95%;
                            display:none;
                            margin: 0 auto;
                            padding:0 0.5em;
                        ">
                        <h1>{{user.username}}'s Gifts</h1>
                        <div class="gift-wrapper">
                            <div class="list" style="width:100%;">
                                {% for gift in gifts %}
                                    {% cycle 'odd' 'even' as state silent %}
                                    {% if state == 'odd' %}
                                        <div class="well" style="
                                            height: 9em;
                                            width: auto;
                                            margin: 0 auto;
                                            padding: 19px 0;
                                            ">
                                            <div class="col-md-5 profile-gift-well" style="height:100%; width:100%; display-flex; justify-content:space-between;">
                                                {% if gift.gift_image %}
                                                    <img src="{{gift.gift_image.url}}" class="img-responsive" width="100px" alt="">
                                                {% else %}
                                                    {% if gift.gift_audio %}
                                                        <img src="{% static 'gift/img/Shapevibe-Audio.png' %}" class="img-responsive" width="100px" alt="">
                                                    {% else %}
                                                        <img src="{% static 'gift/img/iconMedium.png' %}" alt="" width="100px">
                                                    {% endif %}
                                                {% endif %}
                                                <div class="profile-gift-well-caption" style="display:block; width:60%; font-size: 0.75em;">
                                                    <span class="gift-value" style="color:darkgrey;">{{ gift.created_at }}</span><br>
                                                    <span class="gift-value" style="color:darkgrey;">{{ gift.gift_title|title }}</span>
                                                </div>
                                                <a href="{% url 'gift:detail' gift.id %}"><img src="{% static 'gift/img/eye.png' %}" height="50px" alt=""></a>
                                                <div class="actions">
                                                    <a href="{% url 'gift:edit_gift' gift.id %}"><button class="btn btn-primary" style="padding:5px;"><i class="fa fa-edit"></i></button></a>
                                                    <a href="{% url 'gift:delete_gift' gift.id %}" onclick="return confirm('Are you sure you want to delete gift?')"><button class="btn btn-danger" style="padding:5px;"><i class="fa fa-trash"></i></button></a>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                {% endfor %}
                                </div>
                                <div class="list" style="width:100%;">
                                    {% for gift in gifts %}
                                        {% cycle 'odd' 'even' as state silent %}
                                        {% if state == 'even' %}
                                            <div class="well" style="
                                                height: 9em;
                                                width: auto;
                                                margin: 0 auto;
                                                ">
                                                <div class="profile-gift-well" style="height:100%; width:100%; display-flex; justify-content:space-around;">
                                                    {% if gift.gift_image %}
                                                        <img src="{{gift.gift_image.url}}" class="img-responsive" width="100px" alt="">
                                                    {% else %}
                                                        {% if gift.gift_audio %}
                                                            <img src="{% static 'gift/img/Shapevibe-Audio.png' %}" class="img-responsive" width="100px" alt="">
                                                        {% else %}
                                                            <img src="{% static 'gift/img/iconMedium.png' %}" alt="" width="100px">
                                                        {% endif %}
                                                    {% endif %}
                                                    <div class="profile-gift-well-caption" style="display:block; width:60%; font-size: 0.75em;">
                                                        <span class="gift-value" style="color:darkgrey;">{{ gift.created_at }}</span><br>
                                                        <span class="gift-value" style="color:darkgrey;">{{ gift.gift_title|title }}</span>
                                                    </div>
                                                    <a href="{% url 'gift:detail' gift.id %}"><img src="{% static 'gift/img/eye.png' %}" height="50px" alt=""></a>
                                                    <div class="actions">
                                                        <a href="{% url 'gift:edit_gift' gift.id %}"><button class="btn btn-primary" style="padding:5px;"><i class="fa fa-edit"></i></button></a>
                                                        <a href="{% url 'gift:delete_gift' gift.id %}" onclick="return confirm('Are you sure you want to delete gift?')"><button class="btn btn-danger" style="padding:5px;"><i class="fa fa-trash"></i></button></a>
                                                    </div>
                                                </div>
                                            </div>
                                        {% endif %}
                                    {% endfor %}
                                </div>
                        </div>
                    </div>
                    <div id="giftInfo">
                        <div class="col-md-6 profile-half" style="">

                            {% if gift.gift_image %}
                                <img src="{{gift.gift_image.url}}" class="img-responsive" style="padding: 1em;" alt="">
                            {% else %}
                                {% if gift.gift_audio %}
                                    <img src="{% static 'gift/img/Shapevibe-Audio.png' %}" class="img-responsive" alt="">
                                {% else %}
                                    <img src="{% static 'gift/img/shapeVibe-Logo.png' %}" class="img-responsive" alt="">
                                {% endif %}
                            {% endif %}
                            {% if gift.gift_audio %}
                            <audio controls>
                                <source src="{{ gift.gift_audio.url }}"
                                        {% if audio_file_type == 'mp3' %}
                                            type="audio/mpeg"
                                        {% elif audio_file_type == 'ogg' %}
                                            type="audio/ogg"
                                        {% else %}
                                            type="audio/wav"
                                        {% endif %}
                                >
                            </audio>
                        {% endif %}
                        </div>
                        <div class="col-md-4 profile-half" style="height:100%;">

                            {% if success_message %}
                                <div class="alert alert-success">
                                    {{success_message}}
                                </div>
                            {% endif %}
                            title: <h4 class="gift-value">{{gift.gift_title|title}}</h4>
                            Description: <br> <p><span class="gift-value">{{gift.gift_description}}</span></p>
                            <!--<h6 class="gift-value">Posted by <a href="{% url 'gift:view_profile' gift.user.username %}">{{gift.user}}</a> at {{gift.created_at}}</h6>-->
                            {% if gift.price %}
                                price: <h4 class="gift-value">${{gift.price}}</h4>
                            {% else %}
                                price: <h4 class="gift-value">Free</h4>
                            {% endif %}
                            Posted by: <a href="{% url 'gift:view_profile' gift.user.username %}" class="gift-value">{{ gift.user }}</a>
                            <div class="share" style="background: white; height:100%;">
                                <h3>Share:</h3>
                                <span class='st_facebook_large' displayText='Facebook'></span>
                                <span class='st_twitter_large' displayText='Tweet'></span>
                                <span class="st_googleplus_large" displayText="Google+"></span>
                                <span class="st_reddit_large" displayText="Reddit"></span>
                                <span class="st_email_large" displayText="Email"></span>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="controller" style="
            background: black;
            width: 100%;
            position: fixed;
            bottom: 0;
            left: 0;
            height: auto;">
            <div class="controller-panel" style="
                width:75%;
                background: transparent;
                margin: 0 auto;
                display:flex;
                justify-content: space-between;
                padding:1.5em; 0;">
                <a href="{% url 'gift:view_profile' user.username %}"><img src="{% static 'gift/img/home.png' %}" class="img-responsive" alt=""></></a>
                <a href="" style="padding:0 10px;"><img class="unavailable-content img-responsive" src="{% static 'gift/img/friends.png' %}" alt=""></a>

                <button onclick="showAllGifts()" style="background:transparent;border:none;padding:0 10px;"><img src="{% static 'gift/img/gift.png' %}" class="img-responsive" alt=""></button>


                <a href="" style="padding:0 10px;"><img class="unavailable-content img-responsive" src="{% static 'gift/img/heart.png' %}" alt=""></a>
                <a href="" style="padding:0 10px;"><img class="unavailable-content img-responsive" src="{% static 'gift/img/star.png' %}" alt=""></a>
                <a href="" style="padding:0 10px;"><img class="unavailable-content img-responsive" src="{% static 'gift/img/cloud.png' %}" alt=""></a>
                <a href="" style="padding:0 10px;"><img class="unavailable-content img-responsive" src="{% static 'gift/img/wrench.png' %}" alt=""></a>
            </div>
        </div>
</div>
<script>
    //use in-line js for controller actions on showing specific content
    var x = document.getElementById("giftInfo");
    var y = document.getElementById("giftList");
    var h = document.getElementById("homeIcon");
    var g = document.getElementById("giftIcon");
    var b = document.getElementById("giftButton");
    function showAllGifts() {
        if (y.style.display === 'none'){
            y.style.display = 'block';
            x.style.display = 'none';
            h.style.display = 'none';
            g.style.display = 'block';
            b.style.display = 'block';
        }
    }

    function showProfile() {
        if (y.style.display === 'block') {
            y.style.display = 'none';
            x.style.display = 'block';
            h.style.display = 'block';
            g.style.display = 'none';
            b.style.display = 'none';
        }
    }
</script>
{% endblock %}